"""Seed sample_family_data.py into the backend data files.

Run from the same folder that contains backend.py, classes.py, and sample_family_data.py:

    python seed_sample_data.py

The script uses backend.add_person and backend.init_family instead of writing
family/person JSON files directly. The sample identifiers p0/f0/... are treated
as temporary IDs and are remapped to the real IDs generated by the backend.
"""

from __future__ import annotations

from copy import deepcopy

from backend import add_person, init_count_file, init_family, start, upd_info_person
from sample_family_data import families, people


RELATION_KEYS = ["father", "mother", "siblings", "partners", "kids"]


def remap_relation_value(value, old_to_new: dict[str, str]):
    """Convert temporary person IDs in one relation field to backend-generated IDs."""
    if value is None:
        return None
    if isinstance(value, list):
        return [old_to_new[item] for item in value if item in old_to_new]
    return old_to_new.get(value)


def remap_family_relations(family, old_to_new: dict[str, str]) -> dict[str, dict]:
    """Convert a sample Family.relations dictionary to backend-generated person IDs."""
    new_relations: dict[str, dict] = {}

    for old_person_id, relation in family.relations.items():
        if old_person_id not in old_to_new:
            continue

        new_person_id = old_to_new[old_person_id]
        new_relations[new_person_id] = {
            key: remap_relation_value(relation.get(key), old_to_new)
            for key in RELATION_KEYS
        }

    return new_relations


def seed_sample_data() -> tuple[dict[str, str], dict[str, str]]:
    """Add the sample people and families to the existing backend files.

    Returns:
        old_to_new_people: maps sample person IDs, e.g. p0, to generated IDs.
        old_to_new_families: maps sample family IDs, e.g. f0, to generated IDs.
    """
    start()
    init_count_file()

    old_to_new_people: dict[str, str] = {}
    old_to_new_families: dict[str, str] = {}

    # 1) Create each unique person once.
    for old_person_id, sample_person in people.items():
        health_info = deepcopy(sample_person.health_info or {})

        created_person = add_person(
            sample_person.name,
            birth=sample_person.birth,
            death=sample_person.death,
            blood_type=health_info.get("blood_type"),
            diseases=health_info.get("diseases", []),
            photo="",  # requested: only photo is empty
        )

        old_to_new_people[old_person_id] = created_person.identifier

        # Optional but useful: add_person only stores blood_type and diseases.
        # This preserves any extra health_info fields from the sample data.
        upd_info_person(
            created_person.identifier,
            health_info=health_info,
            photo="",
        )

    # 2) Create each family using the newly generated person IDs.
    for old_family_id, sample_family in families.items():
        new_members = [old_to_new_people[old_id] for old_id in sample_family.members]
        new_relations = remap_family_relations(sample_family, old_to_new_people)

        created_family = init_family(
            sample_family.name,
            members=new_members,
            relations=new_relations,
        )

        old_to_new_families[old_family_id] = created_family.identifier

    return old_to_new_people, old_to_new_families


if __name__ == "__main__":
    people_map, family_map = seed_sample_data()

    print("People ID map:")
    for old_id, new_id in people_map.items():
        print(f"  {old_id} -> {new_id}")

    print("\nFamily ID map:")
    for old_id, new_id in family_map.items():
        print(f"  {old_id} -> {new_id}")
